### ISSUE TITLE
Feature: User can sign up

### ISSUE THREAD

**Issue by AnthonyVNgo** [AnthonyVNgo/final-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can sign up if they're a new user

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user lands on the login / sign up page and will be able to enter their credentials to sign up if they're a new user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/99709530/171967549-c85dafab-19ce-439f-a804-5a90c900313f.png">

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/99709530/171967581-2b820e88-53fa-45bc-b8f7-92d28793851d.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database
- [x] Ensure that new user credentials are stored in the database 

### ☁️ Server
- [x] Add api route for POST requests and test with httpie
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a top navigation bar that includes a hamburger menu
- [x] Add dropdown functionality to the hamburger menu
- [x] Add Sign-up option to the hamburger dropdown menu 
- [x] Handle hash routing for view swap between gallery view and profile view and sign up view
- [x] Create a signup page to handle sign-ups

### 🧑‍⚕️ Clean Up
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
