### ISSUE TITLE
Feature: User can add categories to their now entries

### ISSUE THREAD

**Issue by AnthonyVNgo** [AnthonyVNgo/final-project#18]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can share a brief written description of their current projects (nowwws) AND categorize them by selecting icons

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user can share what they're working on by clicking on the add a Nowww button. Once they click on the button, they're able to write within a text input AND select from a dropdown of pre-set categories (including a custom / misc category)

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/99709530/171968824-9f552926-15a2-4490-b44a-86ddcf245676.png">

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/99709530/171968834-2239d813-2f32-4512-af49-8584f846a2eb.png">

<img width="1120" alt="image" src="https://user-images.githubusercontent.com/99709530/171968807-ae7e0d36-d27d-4e05-825c-c60e525dbf71.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [ ] Insert Nowww entries plus categories  into the Nowww table with corresponding userId and content

### ☁️ Server

- [ ]  Add api route for PUT ('/api/auth/my-now/new-entry') requests and test with httpie
(for inserting current user's Nowww entries into the Nowww table with corresponding userId and content)
- [ ]  Test with HTTPie
- [ ]  Handle all errors and respond to the client

### ⚡ Client

- [ ] Create a component to ...
- [ ] Update component to ...

### 🧑‍⚕️ Clean Up

- [ ] ... 
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
