### ISSUE TITLE
Feature: User can view their nowww entries as a list

### ISSUE THREAD

**Issue by AnthonyVNgo** [AnthonyVNgo/final-project#19]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can see their nowww entries rendered as a list item

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user completes a submission for the nowww entry while on the edit nowww page. If the user refreshes the edit-nowww page, views the my-nowww page, or views their card through the nowww-gallery, they will be able to see their nowww-entries displayed in a list component.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="545" alt="image" src="https://user-images.githubusercontent.com/99709530/175183315-b02e27e4-ce5c-47cb-a072-4df7ed7b5b9c.png">

<img width="1219" alt="image" src="https://user-images.githubusercontent.com/99709530/175183464-86f06c21-2547-415d-ad74-dbe0868f4a36.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x]  Add api route for GET ('/api/auth/entry-list) requests and test with httpie
(for getting current logged in user's now entry data and populating the list component) 
- [x] Test with HTTPie
- [x]  Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to display the user's now entry as a list 
- [x] Update now-entry-from component's onSubmit / handleSubmit method to ensure operations align with list rendering
- [x] Ensure that gallery card view and my nowww view's componentDidMount method includes a GET request to ('/api/auth/entry-list)
- [x] Include token during get request

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
