### ISSUE TITLE
Feature: User can delete their current projects (Nowwws)

### ISSUE THREAD

**Issue by AnthonyVNgo** [AnthonyVNgo/final-project#21]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can delete their nowww entries.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

To delete an entry, the user will be in the edit nowww view. Their nowww entries list will render their list items. The list items will now include an "x/trash" icon button. The user can click on the "x/trash" icon to delete their nowww entry. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="517" alt="image" src="https://user-images.githubusercontent.com/99709530/175610785-1526dba6-30cc-46fd-b081-822582162167.png">

<img width="1234" alt="image" src="https://user-images.githubusercontent.com/99709530/175610515-b54a37ae-7c0a-4fdc-9dc5-430114719490.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [ ] Delete Nowww entries from the Nowww table with corresponding userId and content

### ☁️ Server

- [ ] Add api route for DELETE ('/api/now-entry/:entryId') requests and test with httpie
(for deleting the current user's Nowww entries from the Nowww table with corresponding userId and content)
- [ ] Test with HTTPie
- [ ]  Handle all errors and respond to the client

### ⚡ Client

- [ ] Update nowww entries list item component to display "x/trash" icon while on the edit-nowww page
- [ ] Add an onClick handler method that sends a DELETE request to ('/api/now-entry') with the correct entry values
- [ ] Include the token in the request headers

### 🧑‍⚕️ Clean Up

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
