### ISSUE TITLE
Feature: User can create a bio

### ISSUE THREAD

**Issue by AnthonyVNgo** [AnthonyVNgo/final-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can create a bio that provides the option to include a link, location, & tagline, as well as a brief description of what they do and why they're doing what they do

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user logs in or registers, uploads their photo (optional), and includes a general overview of themselves for other users to see. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/99709530/171968505-8244999e-c9fc-4290-9e69-5415c6d2c6d7.png">

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/99709530/171968525-90a154f1-da04-4111-82e6-7122f062e6e3.png">

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/99709530/171968544-bdde4312-21d9-4efa-ac3f-42962b5d1f99.png">

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/99709530/171968561-9bae691f-28b8-4fb5-acc0-673918339696.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Insert user details into the appropriate columns in the users table and the corresponding userId row

### ☁️ Server

- [x] Add api route for POST ('/api/auth/my-now:user-id') requests and test with httpie
(for inserting current logged in user's data into the user table and corresponding userId row)
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Update the user details component UI to provide input and form submission functionality 
- [x] Ensure user details component has handlers for form submission to store input entries

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
