### ISSUE TITLE
Feature: User can share current projects (nowwws)

### ISSUE THREAD

**Issue by AnthonyVNgo** [AnthonyVNgo/final-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can share a brief written description of their current projects (nowwws)

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user can share what they're working on by clicking on the add a Nowww button. Once they click on the button, they're able to write within a text input

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/99709530/171968824-9f552926-15a2-4490-b44a-86ddcf245676.png">

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/99709530/171968834-2239d813-2f32-4512-af49-8584f846a2eb.png">

<img width="1120" alt="image" src="https://user-images.githubusercontent.com/99709530/171968807-ae7e0d36-d27d-4e05-825c-c60e525dbf71.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Insert Nowww entries into the Nowww table with corresponding userId and content

### ☁️ Server

- [x]  Add api route for POST ('/api/my-now/new-entry') requests and test with httpie
(for inserting current user's Nowww entries into the Nowww table with corresponding userId and content)
- [x]  Test with HTTPie
- [x]  Handle all errors and respond to the client

### ⚡ Client

- [x] Create a form / list component to handle up to 10 max Nowww entries 
- [x] Add a submit handler method that sends a POST request to ('/api/my-now/new-entry') with the input values
- [x] Include the token in the request headers

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
