### ISSUE TITLE
Feature: User can view Nowww gallery

### ISSUE THREAD

**Issue by AnthonyVNgo** [AnthonyVNgo/final-project#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view a gallery of other nowww profiles

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user can browse a gallery of profiles by clicking on the Nowww logo in the navbar. The user will be able to search through pages rather then going through an infinite scroll.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/99709530/171969192-3e1a5654-f651-4345-994b-d31d88a48fb2.png">

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/99709530/171969205-6fe42aac-95f2-47e0-a18b-41b8f70f558f.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Insert dummy data for the server to load

### ☁️ Server

- [x] Add api route for GET requests and test with httpie

### ⚡ Client

- [x] Create a card component to display users & their bios
- [x] Create and display a "list" of card components
- [x] Write the client code, including fetching the data from the server

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
