### ISSUE TITLE
Feature: User can view other profiles

### ISSUE THREAD

**Issue by AnthonyVNgo** [AnthonyVNgo/final-project#7]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can click on and view other nowww profiles

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

After exploring the nowww profile gallery, the user will have the option to view other user profiles

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/99709530/171969287-dd06b15a-fba8-437b-b327-15a68c4deac1.png">

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/99709530/171969271-a0c5f2e9-9078-45f3-9d2e-9b2f96eee140.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Add api route for GET requests for the route path (/api/users/:userId) and test with httpie

### ⚡ Client

- [x] Create a component to handle user profile view
- [x] Handle hash routing for view swap between gallery view and profile view (#profile?userId=${someUserId})

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
